### ISSUE TITLE
Warning if script file is empty

### ISSUE THREAD

**Issue by zorantica** [daust/opal-tools#100]
Hi Dietmar!

It would be nice if OPAL warns about empty script files in patch... maybe appropriate location will be when a list of scripts is displayed before actually installing them:

![image](https://user-images.githubusercontent.com/33637578/113727138-24979580-96f5-11eb-939b-3fc386e3590f.png)

Otherwise Your OPAL tool is fantastic! It is helping us A LOT for patches deployment.
Thank You!

**Comment by daust** [comment]
Hi Zoran, 

is checking for the byte size>0 enough ... or do I need to read the file and trim it? My current implementation only checks for 0 bytes, then you get the following message AT THE END of the first pass: 

![image](https://user-images.githubusercontent.com/4840057/151332558-2f15c25b-9b15-4d9e-aeae-79430ac8a2d4.png)

This way it isn't overlooked that easily. 

Best, 
~Dietmar.

**Comment by zorantica** [comment]
This is a perfect solution! Thank You!
