### ISSUE TITLE
Manual install script

### ISSUE THREAD

**Issue by agrlica** [daust/opal-tools#101]
We are now using opal-tools on multiple projects. Usually, it's enough to prepare a patch and install it with opal-tools installer.

But on a few occasions, we run onto clients which would like to run themselves patch script. They don't have opal-tools but just sysdba / user access to the database. Those people are used to get one script to install a patch or at least one command to install all subscripts.

So I suggest adding one more option to prepare inside patch like 1.copy-source-files adding new option 99.build-manual-install
This can be archived with two different approaches
1. Some mechanism which prepares a script to run patch without opal-installer (additional install.sql)
2. Join all scripts from the patch in one single file

It's open for debate which approach is better, but I prefer 1. approach for easier customization if needed. The only problem I can think of is different charsets (script / apex UTF8). But that is for opal-tools users to decide if "manual install" is needed.

That way we can internally use opal-tools for development, and then deliver patches to the clients.

Let me know what do you think about this idea.

Kind regards,
Andej

**Comment by daust** [comment]
It is a great idea ... already had in the back of my mind. Good, that you have an actual use case for it, so now we can actually implement and test it :).

**Comment by daust** [comment]
We still need to discuss it. I just read your feature request again. You want to connect using SYSDBA (and possibly use ``alter session set schema=...```). But we assume that you will connect with each user separately. We can support proxy connects but not really the sysdba approach like this from my point of view.

**Comment by daust** [comment]
You can find it in the documentation under: "Create Distribution Zip File for Manual Installation"

In the patch template you can use the script ``4.export-scripts-for-manual-install.cmd``.
