### ISSUE TITLE
Upgrade to SQLcl 22.2 to support new APEX export arguments

### ISSUE THREAD

**Issue by Mabktst** [daust/opal-tools#115]
APEX 22.1 comes with new readable exports types YAML and JSON. The new parameters documented here: https://docs.oracle.com/en/database/oracle/application-express/22.1/aeadm/exporting-one-or-more-applications.html are support in SQLcl 22.1. I replaced the libraries in opal-tools\lib and was able to use expType. Would be great to get this in the offical opal-tools release. Thanks.

**Comment by daust** [comment]
I have upgraded to sqlcl 22.2.1.

**Comment by daust** [comment]
Well, I have tried updating to 22.2.1 but ran into issues. Seems to work fine with 22.1.1.
