### ISSUE TITLE
Changing encrpytion key from ip address to encryption file

### ISSUE THREAD

**Issue by daust** [daust/opal-tools#13]
Currently, one of the user specific encryption keys is the ip address. This works fine for server based installations because the ip address typically remains stable. But on laptops this is an issue because people change networks and then it would not work. 

Thus, it is better to use the MAC address of the network card. 

https://mkyong.com/java/how-to-get-mac-address-in-java/

**Comment by daust** [comment]
The MAC address is not a safe choice either. Each developer laptop can have multiple network cards, at least one for Ethernet and another one for Wi-Fi. 

It would be a better choice to generate a file with an initial random salt that is used to encrypt and decrypt.

**Comment by daust** [comment]
a file keys.txt will be generated in the user-conf directory, next to the connection pools.

**Comment by grlicaa** [comment]
after changing password in OPAL tools 2.0.0 connection-poll.json  and opal-export execution JSON file get additional not needed data.
Sample  :
{
  **"sqlDir": "sql",
  "traversalType": "INORDER",**
  "targetSystem": "dev",
  "connectionPools": [
    {
      "name": "andrejgr",
      "user": "andrejgr",
      "password": "test",
      "connectString": "jdbc:oracle:thin:@db_high?TNS_ADMIN=\"C:\\\\Oracle\\\\cloud\\\\andrejgr\""
    }
  ],
  **"sqlFileRegEx": "\\.(sql|pks|pkb)$",
  "waitAfterEachStatement": "false"**
}

**Comment by daust** [comment]
This is fixed in 2.1.0 through #14 .
