### ISSUE TITLE
export error with JOBs

### ISSUE THREAD

**Issue by daust** [daust/opal-tools#25]
While exporting I had errors only with “LOB” and “JOB” object_type (We have on that schema almost 100 jobs, non of them where exported), schema2ddl export that out.

Almost all finished with following error 
export: SEND_FLEXMAIL_QUEUE[JOB]             => 20:00:20 (Exporter,ERROR) sql error: ORA-31600: invalid input value SEND_FLEXMAIL_QUEUE for parameter NAME in function GET_DDL
ORA-06512: at "SYS.DBMS_METADATA", line 6681
ORA-06512: at "SYS.DBMS_SYS_ERROR", line 105
ORA-06512: at "SYS.DBMS_METADATA", line 6558
ORA-06512: at "SYS.DBMS_METADATA", line 9672
ORA-06512: at line 1

**Comment by grlicaa** [comment]
Sample JOB : 
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
            job_name => '"MBA".""',
            job_type => 'STORED_PROCEDURE',
            job_action => 'MBA.AUC_PRE_INTERFACE.REFRESH_PRE_ALL',
            number_of_arguments => 0,
            start_date => TO_TIMESTAMP_TZ('2020-11-03 08:40:08.000000000 EUROPE/PRAGUE','YYYY-MM-DD HH24:MI:SS.FF TZR'),
            repeat_interval => 'FREQ=HOURLY',
            end_date => NULL,
            enabled => FALSE,
            auto_drop => TRUE,
            comments => 'Refresh webpage data by hour.');

         
     
 
    DBMS_SCHEDULER.SET_ATTRIBUTE( 
             name => '"MBA".""', 
             attribute => 'store_output', value => TRUE);
    DBMS_SCHEDULER.SET_ATTRIBUTE( 
             name => '"MBA".""', 
             attribute => 'logging_level', value => DBMS_SCHEDULER.LOGGING_OFF);
      
   
  
    
    DBMS_SCHEDULER.enable(
             name => '"MBA".""');
END;
/

**Comment by daust** [comment]
The object types differ between ALL_OBJECTS and DBMS_METADATA. A mapping between the two fixed it.
