### ISSUE TITLE
Executable "test_passwords" or "encrypt_passwords"

### ISSUE THREAD

**Issue by grlicaa** [daust/opal-tools#57]
Since we can have multiple connection pools and inside connection pools multiple schema passwords. Even worse when we have proxy user for all connections and we need to change all passwords at the same time.

It would be much appreciated and easier once we change password that we can execute "test_passwords" or at least "encrypt_passwords" so we don't need to wait for first execution of export or install script. 
setting can be among "user-config" files.

**Comment by daust** [comment]
two new files will be created in the opal-tools/bin directory: 
* opal-validate-connections.cmd (simple wrapper for the Java class)
* validate-connections.cmd (contains the call to validate all know connection pools)

e.g.: 
```
@call "c:\app\project1 und 1\conf-user\setProjectEnvironment.cmd"

@call opal-validate-connections.cmd "%OPAL_TOOLS_USER_CONFIG_DIR%\connections-dev.json" "%OPAL_TOOLS_USER_CONFIG_DIR%\connections-test.json" 

cmd /k
```

All connection files can be passed on the command line. This way we are totally flexible, what we want to encrypt/validate and what not. By default we generate all connection pool filenames that were set up during the initial setup.
