### ISSUE TITLE
Patch dependency

### ISSUE THREAD

**Issue by grlicaa** [daust/opal-tools#61]
Since we have multiple patches on same project, common mistake is that we forget or even don't know (if somebody else prepared patch) what is correct order to install patch on environment.

To make less mistakes it would be great to have some option like "dependency" parameter among application, patch name, 
author and version.

I suggest to add parameter "dependency" in opal-installer.json 
sample :
<pre>
{
  "application": "",
  "patch": "MOY-202009",
  "author": "Andrej Grlica",
  "version": "1.2",
  "dependency":[ "MOY-1829-1.0", "MOY-1767 - xlsx upload images"],
  "connectionMappings": [
   ...
 </pre>

In this case we could validate if those patches are already installed on selected environment. So when you are trying to install on PROD you are sure that all listed patches are installed before this one.
Dependency parameter have seance to use only is you specify "registryTargets".

**Comment by daust** [comment]
implemented. 

You can define multiple dependencies based on the attributes "application", "patch" and "version": 
```
{
  "application": "Project1",
  "patch": "#PARENT_FOLDER_NAME#",
  "author": "#ENV_OPAL_TOOLS_USER_IDENTITY#",
  "version": "1.0.0",
  "connectionMappings": [
    {
      "connectionPoolName": "jri_test",
      "matchRegEx": "/sql/.*jri_test.*"
    }
  ],
  "sqlFileRegEx": "\\.(sql|pks|pkb|trg)$",
  "waitAfterEachStatement": "true",
  "registryTargets": [
    {"connectionPoolName": "jri_test",
      "tablePrefix": "OPAL2"}],
  "encodingMappings": [
    {
      "encoding": "UTF-8",
      "matchRegEx": "/sql/.*apex.*/.*f*sql",
      "description": "encoding for APEX files is always UTF8"
    },
    {
      "encoding": "UTF-8",
      "matchRegEx": "/sql/.*",
      "description": "all other files will get this explicit mapping"
    }
  ],
  "patchDependencies": [{"application": null, "patch":"2020-11-12-test 123", "version": "123"},
                        {"patch":"2020-11-12-test 123"},
                        {"application": "test1"}]
}
```
The base query for checking is: 
```
select count(*) 
  from #PREFIX#_installer_patches 
where (     pat_application=nvl(?,pat_application) 
            and pat_name=nvl(?,pat_name) 
            and pat_version=nvl(?,pat_version) 
            and pat_target_system=?)
```

**Comment by daust** [comment]
should we also use the opposite ... which patches MUST not be installed? E.g. the current one?

something like: 
```
includedDependencies: []
excludedDependencies: []
```
or 
```
requiredDependencies: []
forbiddenDependencies: []
```
or 
```
requiredPatches: []
forbiddenPatches: []
```
???

**Comment by daust** [comment]
I have changed it from
```
{
...
  "patchDependencies": [{"application": null, "patch":"2020-11-12-test 123", "version": "123"},
                        {"patch":"2020-11-12-test 123"},
                        {"application": "test1"}]
}
```
to 
```
{
...
  "dependencies": [{"application": null, "patch":"2020-11-12-test 123", "version": "123"},
                        {"patch":"2020-11-12-test 123"},
                        {"application": "test1"}]
}
```
