### ISSUE TITLE
external ID and exta options

### ISSUE THREAD

**Issue by grlicaa** [daust/opal-tools#66]
In case when we have external application for creating patches, we need to have some column to match with our system.

I suggest that OPAL-installer.json have additional columns 
1. externalID :"" (string type)
2. extra: {} (JSON type) (to be more flexible on different environments, projects)

For checking mandatory options we can use "extra" for any data at all or also add more specific like "extra.id" "extra.description"...

Also please include those columns in table "opal_installer_patches".

**Comment by daust** [comment]
Implemented as: 
- "referenceId" varchar2(100 char)
- "extra" varchar2(4000 char)

extra is implemented as string, should be fine for now. Could be extended later as CLOB.  Not as JSON type, converting on the fly should be ok. Also, some people might choose a different encoding, not JSON but simple comma or colon separated list. Whatever.

**Comment by daust** [comment]
The checking for attributes inside the JSON string is more difficult. But ``referenceId`` can already now be used as a mandatory attribute. 

Both parameters are included in the default template, documentation is also updated. 
![image](https://user-images.githubusercontent.com/4840057/100360471-45d6cf80-2ff9-11eb-937a-b4db66009c4e.png)

**Comment by daust** [comment]
the table definitions are also added in the docs:
![image](https://user-images.githubusercontent.com/4840057/100360634-73bc1400-2ff9-11eb-9783-caba9756d0e7.png)

**Comment by daust** [comment]
The parameter ``referenceId`` is also added to the query with the dependencies.
