### ISSUE TITLE
Referencing patch files instead of copying them

### ISSUE THREAD

**Issue by daust** [daust/opal-tools#69]
Sometimes developers don't want to copy the files into the patch but reference them in the patch only. 

Using 
```
@../packages/my_package.sql
```
is an approach to install a file that resides in the source tree and not in the patch tree. 

One option to implement that would be to use the ``PatchFiles.txt`` file not only for copying the files but also to reference them while running the installer. 

The file listing from ``PatchFiles.txt`` could be merged with the actual files from the patch files ... and installed depending on their combined sort order. 

This could either be implemented for the whole file by providing a copy/reference mode to either copy or only reference the files. 
Or it could be done on a folder or individual file level. Then we would need a specific syntax for the files, e.g. : 
```
C:xlib*.pks
```
to copy files and 
```
R:xlib*.pks
```
to only reference files.

**Comment by rimblas** [comment]
I like this enhancement, but I would argue that, when using version control, this should be the default behavior. Copying sources to the patch only makes sense when you don’t use version control.

**Comment by daust** [comment]
I agree. At the same time more people will use the copy approach and not use more sophisticated methods. This is just my experience. 

Anyhow, when I implement both approaches you can easily choose your approach. Only once you have to modify the patch template (and only delete what you don't need) and you are good to go. 

I deal with the reference files in the following manner: 

1. I look at the ``SourceFilesReference.txt`` file and virtually make a list of the files ... and the target locations (as if I would copy them to the target directory). This is important for sorting because the referenced files should also adhere to the sort order ... just as if they were copied. Tables before views before packages, etc. 
2. I display the list of files as if they were copied. In brackets you can see which file is referenced)
3. I execute the referenced file together with the other files in the patch folder (as if both were in the patch folder).

This is the result when you run the ``2.validate.sh`` or ``3.install.sh``: 
![image](https://user-images.githubusercontent.com/4840057/100527738-9571f280-31d5-11eb-9cec-1c0036d2b516.png)

You can pass the file ``SourceFilesReference.txt`` and the source directory on the command line. You just have to fill in the files you want to reference in the patch. This file is automatically picked up by the generated shell scripts: 

![image](https://user-images.githubusercontent.com/4840057/100527774-f4d00280-31d5-11eb-8652-b22383e0e3ce.png)

Then ``1.copy-patch-files.sh`` will pick up a different file with the same contents. It used to be PatchFiles.txt and now we have two files instead: 
- SourceFilesCopy.txt (picked up by 1.copy-patch-files)
- SourceFilesReference.txt (picked up by 2.validate and 3.install)

![image](https://user-images.githubusercontent.com/4840057/100527799-35c81700-31d6-11eb-9931-c4d875a89763.png)

Whatever you fill in ... will get picked up.  

![image](https://user-images.githubusercontent.com/4840057/100527810-57290300-31d6-11eb-81a1-6496666938e0.png)

I like that feature ... great feedback 👍

**Comment by daust** [comment]
The virtual merging of files works great. In this sample I have a script to ``alter table add column`` in the patch subdirectory: 

![image](https://user-images.githubusercontent.com/4840057/100538768-f7f8dc00-3231-11eb-8d88-805274326c96.png)

The rest of the files come from the file ``SourceFilesReference.txt``: 
![image](https://user-images.githubusercontent.com/4840057/100538800-270f4d80-3232-11eb-97ac-6fcee3bf249a.png)

Here is the log of which files are installed in which order: 
![image](https://user-images.githubusercontent.com/4840057/100538830-57ef8280-3232-11eb-8964-3cf9982c3e8a.png)

The ``alter-table-statements.sql`` fits nicely into the sorted (virtual list) of the files from both directories.  

Now we have a clean separation between purely patch-specific files and the source files from the source tree. 

And if you so choose to, you can use the contents of the ``SourceFilesReference.txt`` for the copy command. The different approach remain possible, you can pick and choose.
