### ISSUE TITLE
Installer --silent

### ISSUE THREAD

**Issue by grlicaa** [daust/opal-tools#78]
At the moment we are missing installation option --silent

Sometimes you don't wont click 200 times on all objects during installation.
I know it's better to run it without that option for security reason.As default I suggest we don't use it but you can if you know what are you doing.
So with this option I would expect to wait for first "enter" right after process specification and after that install all objects without confirmation in between.

**Comment by daust** [comment]
As discussed, it is already possible (although not too obvious). The switch is included in the ``opal-installer.json`` file: ``"waitAfterEachStatement":"false"``

I will make the following changes: 
- remove ``waitAfterEachStatement`` from ``opal-installer.json``
- set default for ``waitAfterEachStatement`` to ``true`` if it does not exist in the .json file
- add command line switches
   - ``--silent``
   - ``--silent-after-header``

to the installer and exporter (``--silent`` is already implemented for the exporter)

**Comment by daust** [comment]
I have implemented it now, the naming changed slightly:
```
 --silent                                         : disable all prompts, non-interactive mode (Vorgabe: false)
 --silent-execution                               : prompt after header information, execute all scripts without prompt.
```
