### ISSUE TITLE
matchRegEx case-insensitive

### ISSUE THREAD

**Issue by grlicaa** [daust/opal-tools#79]
Today we had a case when user prepared patch with naming of schema in uppercase.
sql/10_MBA   (MBA is schema name)

settings inside Opal-installer.json where set to :
```JSON
  "connectionMappings": [
    {
      "connectionPoolName": "mba",
      "matchRegEx": "\\\\sql\\\\.*mba.*"
    },
    {
      "connectionPoolName": "auctim",
      "matchRegEx": "\\\\sql\\\\.*auctim.*"
    }
  ]
```
We spend some time on figuring this out, but for future reference I would suggest that "matchRegEx" inside "connectionMappings" and "encodingMappings" is changed to case insensitive.

**Comment by daust** [comment]
Did you turn on debugging? Then you should see which regular expression is tested ... easier to figure out, what is going wrong.
