### ISSUE TITLE
Source file reference validation

### ISSUE THREAD

**Issue by AKravos** [daust/opal-tools#90]
As an enhancement, I would like to see a validation on the SourceFilesCopy.conf to prevent files not being copied in case I made a typo. The validation should in my opinion occur when running the copy-source-files command.

**Comment by daust** [comment]
Yes. I will implement it so that the validation cannot be overridden or turned off. Should always make sense. 

Not sure yet how to deal with ``*``. Could raise an error when the directory is empty ... or not?
